### ISSUE TITLE
请问 ItemsManage 自用物品管理器/修改器 怎么使用? 我找不到 config file

### ISSUE THREAD

**Issue by newbienoobplayer** [kumor00/ItemsModifyTool#1]
如题

**Comment by kumor00** [comment]
下载二进制文件，选取需要的功能dll就可以游玩了。
编译的话下载整个仓库，配置好游戏的库引用。
不清楚你说的config file是什么，ItemsManage项目里面配置相关的只有ItemConfig.cs

**Comment by kumor00** [comment]
游玩所需的几个前置依赖
[BepInEx](https://dsp.thunderstore.io/package/xiaoye97/BepInEx/)
[LDBTool](https://dsp.thunderstore.io/package/xiaoye97/LDBTool/)
[CommonAPI](https://dsp.thunderstore.io/package/CommonAPI/CommonAPI/)
[CommonAPI-DSPModSave](https://dsp.thunderstore.io/package/CommonAPI/DSPModSave/)

**Comment by newbienoobplayer** [comment]
你好大佬我现在声明一下我是菜逼我不怎么懂这些代码，还请见谅

我该有的前置文件我都有，![image](https://github.com/kumor00/ItemsModifyTool/assets/138718840/f8557bf1-0bba-4c0f-9159-80f15f43de92)

![Screenshot (380)](https://github.com/kumor00/ItemsModifyTool/assets/138718840/aa4c6dd7-0d04-4a80-bdc2-12bcaf3dadf0)
![Screenshot (381)](https://github.com/kumor00/ItemsModifyTool/assets/138718840/89c33a9b-69a5-4e5d-a94b-25445548a613)





而且根据我对mod理解把mod装上然后运行一下游戏,在config文件里面就会出现该mod，相关的config文件
然后就可以打开config文件修改里面的数值

![Screenshot (382)](https://github.com/kumor00/ItemsModifyTool/assets/138718840/8515d6e0-9ad6-4796-8641-3ba1b26aeadd)
还有我打开ddl文件的时候全是乱码，我不知道要怎么修改
![image](https://github.com/kumor00/ItemsModifyTool/assets/138718840/ee7659b4-a8a8-43d1-82cc-9fa05f940d45)

**Comment by kumor00** [comment]
ItemsManage这个mod没有可配置选项，所有数值都是代码里配置好的，想要修改只能重新编译dll
CustomCreateBirthStar 自定义星区 这个也是前置，行星矿机的合成材料里有一个物品是这个mod里的，不安装会导致无法造这个建筑
\BepInEx\plugins 是存放游戏mod的路径，里面都是dll文件，无法收到打开编辑
\BepInEx\config 才是配置文件路径，里面都是类似kumor.plugin.CustomCreateBirthStar.cfg这样的文件，可以用记事本编辑

**Comment by newbienoobplayer** [comment]
那请问为什么叫自用物品管理器和修改器？，这名字我乍一看还以为是像风灵月影中那样子能让我改数值的

**Comment by kumor00** [comment]
主页有功能说明 [链接](https://github.com/kumor00/ItemsModifyTool#itemsmanage-%E8%87%AA%E7%94%A8%E7%89%A9%E5%93%81%E7%AE%A1%E7%90%86%E5%99%A8%E4%BF%AE%E6%94%B9%E5%99%A8)
配置参数都在源码里修改，所以是自用。它负责修改游戏内和其它新增的物品参数，所以叫物品管理器
